[package]
name = "fast-can"
version = "0.1.4"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>", "Fabian Bally <fabian.bally@gmail.com>"]
description = "A CAN signal and definition parser"
repository = "https://github.com/jmagnuson/canparse"
documentation = "https://docs.rs/canparse"
readme = "README.md"
keywords = ["can", "socketcan", "dbc", "parser"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "fastcan"
path = "src/lib.rs"

[[bench]]
name = "canlibrary"
harness = false

[[bench]]
name = "socketcan"
harness = false
required-features = ["use-socketcan"]

[features]
default = []
use-socketcan = ["socketcan"]

[dependencies]
byteorder = "1.3"
encoding = "0.2"
enum_primitive = "0.1"
nom = "4.2"
socketcan = { version = "1.7", optional = true }

[dev-dependencies]
approx = "0.3"
criterion = "0.3"
lazy_static = "1.3"

[package.metadata.docs.rs]
features = ["use-socketcan"]

[badges]
travis-ci = { repository = "fabianbally/fast-can-rs" }
codecov = { repository = "fabianbally/fast-can-rs", branch = "main", service = "github" }
